name: pnldon
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  parse_server_sdk_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/pnld.png
    - assets/malala.jpg
    - assets/tinha.jpg
    - assets/dezmil.jpg
    - assets/nasci.jpg
    - assets/megera.jpg
    - assets/pnld2.png
    - assets/haiti.jpg
    - assets/contos.jpg
    - assets/foto.jpg
    - assets/logopnld2.png
    - assets/narizdevidro.jpg
    - assets/acolinadossuspiros.jpeg
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/4.png
    - assets/5.png
    - assets/6.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
